version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0

    working_directory: ~/rg

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install
          working_directory: ./templates/base-react

      - run:
          name: Run lint
          command: npm run lint
          working_directory: ./templates/base-react

      - run:
          name: Run unit test
          command: npm run test:coverage
          working_directory: ./templates/base-react

      - run:
          name: Build Base-React in production mode
          command: npm run build
          working_directory: ./templates/base-react

      - store_artifacts:
          path: ./templates/base-react/dist/
