version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0

    working_directory: ~/rg/templates/base-react

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-

      - run:
          name: List current dir
          command: pwd && ls -al

      - run: npm install

      - run:
          name: Build Base-React in production mode
          command: npm run build

      - store_artifacts:
          path: dist/
